my_dbt_project:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse      # <--- БЫЛО localhost, СТАЛО clickhouse
      port: 8123
      user: default
      password: clickhouse_pass
      schema: staging
      secure: False
      verify: False
      connect_timeout: 10