version: 2

sources:
  - name: raw_data
    database: raw
    schema: raw
    tables:
      - name: raw_orders
        description: "Raw orders loaded from Postgres"
        columns:
          - name: order_id
            tests:
              - not_null